// Code generated by mdatagen. DO NOT EDIT.

package activedirectoryinvreceiver

import (
	"testing"

	"go.uber.org/goleak"
)

func TestMain(m *testing.M) {
	// go-adsi/comshim retains a COM apartment worker for the process lifetime.
	goleak.VerifyTestMain(m, goleak.IgnoreAnyFunction("github.com/scjalliance/comshim.(*Shim).run.func1"))
